Use mutable borrow results in 'lifetime static required' error
The error is:
```
error[E0621]: explicit lifetime required in the type of `grid`
  --> src/main.rs:26:7
   |
19 | fn display_curses_grid(siv: &mut cursive::Cursive, grid: &mut Grid) {
   |                                                          --------- help: add explicit lifetime `'static` to the type of `grid`: `&'static mut std::vec::Vec<std::vec::Vec<bool>>`
...
26 |   siv.add_global_callback('n', move |s| {
   |       ^^^^^^^^^^^^^^^^^^^ lifetime `'static` required
```